zone_name        = "example_zone"
zone_description = "This is an example management zone"
zone_legacy_id   = "legacy-id-example"
entity_selector  = ""
dynatrace_api_url   = "https://yourenv.live.dynatrace.com/api"
dynatrace_api_token = "your-api-token"